[variables]
PYTHONPATH = "/app/backend"

[providers]
python = "3.12"

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "gcc", "curl"]

[phases.install]
cmds = [
  "cd backend",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd backend",
  "echo 'Build completed'"
]

[start]
cmd = "cd backend && python production_server.py" 