[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python production_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = "8000"
HOST = "0.0.0.0"
DEBUG = "False"
PYTHONPATH = "/app/backend" 