[build]
builder = "nixpacks"

[deploy]
startCommand = "python production_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
# Production environment variables will be set in Railway dashboard
PORT = "8000"
HOST = "0.0.0.0"
DEBUG = "False"
