// Instructions: Update Railway configuration with proper start command

[build]
builder = "nixpacks"

[deploy]
startCommand = "python production_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = "8000"
HOST = "0.0.0.0"
DEBUG = "False"
PYTHONPATH = "/app"
